/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
 screenfull
 v5.0.0 - 2019-09-09
 (c) Sindre Sorhus; MIT License
*/
(function(){function a(g){g=String(g);return g.charAt(0).toUpperCase()+g.slice(1)}function c(g,r){var x=-1,A=g?g.length:0;if("number"==typeof A&&-1<A&&A<=w)for(;++x<A;)r(g[x],x,g);else h(g,r)}function b(g){g=String(g).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(g)?g:a(g)}function h(g,r){for(var x in g)q.call(g,x)&&r(g[x],x,g)}function p(g){return null==g?a(g):B.call(g).slice(8,-1)}function f(g,r){var x=null!=g?typeof g[r]:"number";return!/^(?:boolean|number|string|undefined)$/.test(x)&&
("object"==x?!!g[r]:!0)}function e(g){return String(g).replace(/([ -])(?!$)/g,"$1?")}function d(g,r){var x=null;c(g,function(A,C){x=r(x,A,C,g)});return x}function m(g){function r(F){return d(F,function(K,L){var Q=L.pattern||e(L);!K&&(K=RegExp("\\b"+Q+" *\\d+[.\\w_]*","i").exec(g)||RegExp("\\b"+Q+" *\\w+-[\\w]*","i").exec(g)||RegExp("\\b"+Q+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(g))&&((K=String(L.label&&!RegExp(Q,"i").test(L.label)?L.label:K).split("/"))[1]&&!/[\d.]+/.test(K[0])&&(K[0]+=
" "+K[1]),L=L.label||L,K=b(K[0].replace(RegExp(Q,"i"),L).replace(RegExp("; *(?:"+L+"[_-])?","i")," ").replace(RegExp("("+L+")[-_.]?(\\w)","i"),"$1 $2")));return K})}function x(F){return d(F,function(K,L){return K||(RegExp(L+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(g)||0)[1]||null})}var A=v,C=g&&"object"==typeof g&&"String"!=p(g);C&&(A=g,g=null);var I=A.navigator||{},k=I.userAgent||"";g||(g=k);var G=C?!!I.likeChrome:/\bChrome\b/.test(g)&&!/internal|\n/i.test(B.toString()),
R=C?"Object":"ScriptBridgingProxyObject",T=C?"Object":"Environment",W=C&&A.java?"JavaPackage":p(A.java),aa=C?"Object":"RuntimeObject";T=(W=/\bJava/.test(W)&&A.java)&&p(A.environment)==T;var O=W?"a":"\u03b1",M=W?"b":"\u03b2",U=A.document||{},P=A.operamini||A.opera,X=u.test(X=C&&P?P["[[Class]]"]:p(P))?X:P=null,l,Y=g;C=[];var Z=null,S=g==k;k=S&&P&&"function"==typeof P.version&&P.version();var J=function(F){return d(F,function(K,L){return K||RegExp("\\b"+(L.pattern||e(L))+"\\b","i").exec(g)&&(L.label||
L)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),D=function(F){return d(F,function(K,L){return K||RegExp("\\b"+(L.pattern||e(L))+"\\b","i").exec(g)&&(L.label||L)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),H=r([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),N=function(F){return d(F,function(K,L,Q){return K||(L[H]||L[/^[a-z]+(?: +[a-z]+\b)*/i.exec(H)]||RegExp("\\b"+e(Q)+"(?:\\b|\\w*\\d)","i").exec(g))&&Q})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),E=function(F){return d(F,function(K,L){var Q=L.pattern||e(L);if(!K&&(K=RegExp("\\b"+Q+"(?:/[\\d.]+|[ \\w.]*)","i").exec(g))){var V=K,ca=L.label||L,da={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};Q&&ca&&/^Win/i.test(V)&&!/^Windows Phone /i.test(V)&&(da=da[/[\d.]+$/.exec(V)])&&(V="Windows "+da);V=String(V);Q&&ca&&(V=V.replace(RegExp(Q,"i"),ca));K=V=b(V.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,
"$1").replace(/\/(\d)/," $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return K})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X",
"Macintosh","Mac","Windows 98;","Windows "]);J&&(J=[J]);N&&!H&&(H=r([N]));if(l=/\bGoogle TV\b/.exec(H))H=l[0];/\bSimulator\b/i.test(g)&&(H=(H?H+" ":"")+"Simulator");"Opera Mini"==D&&/\bOPiOS\b/.test(g)&&C.push("running in Turbo/Uncompressed mode");"IE"==D&&/\blike iPhone OS\b/.test(g)?(l=m(g.replace(/like iPhone OS/,"")),N=l.manufacturer,H=l.product):/^iP/.test(H)?(D||(D="Safari"),E="iOS"+((l=/ OS ([\d_]+)/i.exec(g))?" "+l[1].replace(/_/g,"."):"")):"Konqueror"!=D||/buntu/i.test(E)?N&&"Google"!=N&&
(/Chrome/.test(D)&&!/\bMobile Safari\b/i.test(g)||/\bVita\b/.test(H))||/\bAndroid\b/.test(E)&&/^Chrome/.test(D)&&/\bVersion\//i.test(g)?(D="Android Browser",E=/\bAndroid\b/.test(E)?E:"Android"):"Silk"==D?(/\bMobi/i.test(g)||(E="Android",C.unshift("desktop mode")),/Accelerated *= *true/i.test(g)&&C.unshift("accelerated")):"PaleMoon"==D&&(l=/\bFirefox\/([\d.]+)\b/.exec(g))?C.push("identifying as Firefox "+l[1]):"Firefox"==D&&(l=/\b(Mobile|Tablet|TV)\b/i.exec(g))?(E||(E="Firefox OS"),H||(H=l[1])):!D||
(l=!/\bMinefield\b/i.test(g)&&/\b(?:Firefox|Safari)\b/.exec(D))?(D&&!H&&/[\/,]|^[^(]+?\)/.test(g.slice(g.indexOf(l+"/")+8))&&(D=null),(l=H||N||E)&&(H||N||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(E))&&(D=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(E)?E:l)+" Browser")):"Electron"==D&&(l=(/\bChrome\/([\d.]+)\b/.exec(g)||0)[1])&&C.push("Chromium "+l):E="Kubuntu";k||(k=x(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",e(D),
"(?:Firefox|Minefield|NetFront)"]));if(l="iCab"==J&&3<parseFloat(k)&&"WebKit"||/\bOpera\b/.test(D)&&(/\bOPR\b/.test(g)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(g)&&!/^(?:Trident|EdgeHTML)$/.test(J)&&"WebKit"||!J&&/\bMSIE\b/i.test(g)&&("Mac OS"==E?"Tasman":"Trident")||"WebKit"==J&&/\bPlayStation\b(?! Vita\b)/i.test(D)&&"NetFront")J=[l];"IE"==D&&(l=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(g)||0)[1])?(D+=" Mobile",E="Windows Phone "+(/\+$/.test(l)?l:l+".x"),C.unshift("desktop mode")):/\bWPDesktop\b/i.test(g)?
(D="IE Mobile",E="Windows Phone 8.x",C.unshift("desktop mode"),k||(k=(/\brv:([\d.]+)/.exec(g)||0)[1])):"IE"!=D&&"Trident"==J&&(l=/\brv:([\d.]+)/.exec(g))&&(D&&C.push("identifying as "+D+(k?" "+k:"")),D="IE",k=l[1]);if(S){if(f(A,"global"))if(W&&(l=W.lang.System,Y=l.getProperty("os.arch"),E=E||l.getProperty("os.name")+" "+l.getProperty("os.version")),T){try{k=A.require("ringo/engine").version.join("."),D="RingoJS"}catch(F){(l=A.system)&&l.global.system==A.system&&(D="Narwhal",E||(E=l[0].os||null))}D||
(D="Rhino")}else"object"==typeof A.process&&!A.process.browser&&(l=A.process)&&("object"==typeof l.versions&&("string"==typeof l.versions.electron?(C.push("Node "+l.versions.node),D="Electron",k=l.versions.electron):"string"==typeof l.versions.nw&&(C.push("Chromium "+k,"Node "+l.versions.node),D="NW.js",k=l.versions.nw)),D||(D="Node.js",Y=l.arch,E=l.platform,k=(k=/[\d.]+/.exec(l.version))?k[0]:null));else p(l=A.runtime)==R?(D="Adobe AIR",E=l.flash.system.Capabilities.os):p(l=A.phantom)==aa?(D="PhantomJS",
k=(l=l.version||null)&&l.major+"."+l.minor+"."+l.patch):"number"==typeof U.documentMode&&(l=/\bTrident\/(\d+)/i.exec(g))?(k=[k,U.documentMode],(l=+l[1]+4)!=k[1]&&(C.push("IE "+k[1]+" mode"),J&&(J[1]=""),k[1]=l),k="IE"==D?String(k[1].toFixed(1)):k[0]):"number"==typeof U.documentMode&&/^(?:Chrome|Firefox)\b/.test(D)&&(C.push("masking as "+D+" "+k),D="IE",k="11.0",J=["Trident"],E="Windows");E=E&&b(E)}k&&(l=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(k)||/(?:alpha|beta)(?: ?\d)?/i.exec(g+";"+(S&&I.appMinorVersion))||
/\bMinefield\b/i.test(g)&&"a")&&(Z=/b/i.test(l)?"beta":"alpha",k=k.replace(RegExp(l+"\\+?$"),"")+("beta"==Z?M:O)+(/\d+\+?/.exec(l)||""));if("Fennec"==D||"Firefox"==D&&/\b(?:Android|Firefox OS)\b/.test(E))D="Firefox Mobile";else if("Maxthon"==D&&k)k=k.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(H))"Xbox 360"==H&&(E=null),"Xbox 360"==H&&/\bIEMobile\b/.test(g)&&C.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(D)&&(!D||H||/Browser|Mobi/.test(D))||"Windows CE"!=E&&!/Mobi/i.test(g))if("IE"==
D&&S)try{null===A.external&&C.unshift("platform preview")}catch(F){C.unshift("embedded")}else(/\bBlackBerry\b/.test(H)||/\bBB10\b/.test(g))&&(l=(RegExp(H.replace(/ +/g," *")+"/([.\\d]+)","i").exec(g)||0)[1]||k)?(l=[l,/BB10/.test(g)],E=(l[1]?(H=null,N="BlackBerry"):"Device Software")+" "+l[0],k=null):this!=h&&"Wii"!=H&&(S&&P||/Opera/.test(D)&&/\b(?:MSIE|Firefox)\b/i.test(g)||"Firefox"==D&&/\bOS X (?:\d+\.){2,}/.test(E)||"IE"==D&&(E&&!/^Win/.test(E)&&5.5<k||/\bWindows XP\b/.test(E)&&8<k||8==k&&!/\bTrident\b/.test(g)))&&
!u.test(l=m.call(h,g.replace(u,"")+";"))&&l.name&&(l="ing as "+l.name+((l=l.version)?" "+l:""),u.test(D)?(/\bIE\b/.test(l)&&"Mac OS"==E&&(E=null),l="identify"+l):(l="mask"+l,D=X?b(X.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(l)&&(E=null),S||(k=null)),J=["Presto"],C.push(l));else D+=" Mobile";if(l=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(g)||0)[1]){l=[parseFloat(l.replace(/\.(\d)$/,".0$1")),l];if("Safari"==D&&"+"==l[1].slice(-1))D="WebKit Nightly",Z="alpha",k=l[1].slice(0,-1);else if(k==
l[1]||k==(l[2]=(/\bSafari\/([\d.]+\+?)/i.exec(g)||0)[1]))k=null;l[1]=(/\bChrome\/([\d.]+)/i.exec(g)||0)[1];537.36==l[0]&&537.36==l[2]&&28<=parseFloat(l[1])&&"WebKit"==J&&(J=["Blink"]);S&&(G||l[1])?(J&&(J[1]="like Chrome"),l=l[1]||(l=l[0],530>l?1:532>l?2:532.05>l?3:533>l?4:534.03>l?5:534.07>l?6:534.1>l?7:534.13>l?8:534.16>l?9:534.24>l?10:534.3>l?11:535.01>l?12:535.02>l?"13+":535.07>l?15:535.11>l?16:535.19>l?17:536.05>l?18:536.1>l?19:537.01>l?20:537.11>l?"21+":537.13>l?23:537.18>l?24:537.24>l?25:537.36>
l?26:"Blink"!=J?"27":"28")):(J&&(J[1]="like Safari"),l=(l=l[0],400>l?1:500>l?2:526>l?3:533>l?4:534>l?"4+":535>l?5:537>l?6:538>l?7:601>l?8:"8"));J&&(J[1]+=" "+(l+="number"==typeof l?".x":/[.+]/.test(l)?"":"+"));"Safari"==D&&(!k||45<parseInt(k))&&(k=l)}"Opera"==D&&(l=/\bzbov|zvav$/.exec(E))?(D+=" ",C.unshift("desktop mode"),"zvav"==l?(D+="Mini",k=null):D+="Mobile",E=E.replace(RegExp(" *"+l+"$"),"")):"Safari"==D&&/\bChrome\b/.exec(J&&J[1])&&(C.unshift("desktop mode"),D="Chrome Mobile",k=null,/\bOS X\b/.test(E)?
(N="Apple",E="iOS 4.3+"):E=null);k&&0==k.indexOf(l=/[\d.]+$/.exec(E))&&-1<g.indexOf("/"+l+"-")&&(E=String(E.replace(l,"")).replace(/^ +| +$/g,""));J&&!/\b(?:Avant|Nook)\b/.test(D)&&(/Browser|Lunascape|Maxthon/.test(D)||"Safari"!=D&&/^iOS/.test(E)&&/\bSafari\b/.test(J[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(D)&&J[1])&&(l=J[J.length-1])&&C.push(l);C.length&&(C=["("+C.join("; ")+")"]);N&&H&&0>H.indexOf(N)&&C.push("on "+N);H&&C.push((/^on /.test(C[C.length-
1])?"":"on ")+H);if(E){var ba=(l=/ ([\d.+]+)$/.exec(E))&&"/"==E.charAt(E.length-l[0].length-1);E={architecture:32,family:l&&!ba?E.replace(l[0],""):E,version:l?l[1]:null,toString:function(){var F=this.version;return this.family+(F&&!ba?" "+F:"")+(64==this.architecture?" 64-bit":"")}}}(l=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(Y))&&!/\bi686\b/i.test(Y)?(E&&(E.architecture=64,E.family=E.family.replace(RegExp(" *"+l),"")),D&&(/\bWOW64\b/i.test(g)||S&&/\w(?:86|32)$/.test(I.cpuClass||I.platform)&&!/\bWin64; x64\b/i.test(g))&&
C.unshift("32-bit")):E&&/^OS X/.test(E.family)&&"Chrome"==D&&39<=parseFloat(k)&&(E.architecture=64);g||(g=null);A={};A.description=g;A.layout=J&&J[0];A.manufacturer=N;A.name=D;A.prerelease=Z;A.product=H;A.ua=g;A.version=D&&k;A.os=E||{architecture:null,family:null,version:null,toString:function(){return"null"}};A.parse=m;A.toString=function(){return this.description||""};A.version&&C.unshift(k);A.name&&C.unshift(D);E&&D&&(E!=String(E).split(" ")[0]||E!=D.split(" ")[0]&&!H)&&C.push(H?"("+E+")":"on "+
E);C.length&&(A.description=C.join(" "));return A}var n={"function":!0,object:!0},v=n[typeof window]&&window||this,z=n[typeof exports]&&exports;n=n[typeof module]&&module&&!module.nodeType&&module;var t=z&&n&&"object"==typeof global&&global;!t||t.global!==t&&t.window!==t&&t.self!==t||(v=t);var w=Math.pow(2,53)-1,u=/\bOpera/;t=Object.prototype;var q=t.hasOwnProperty,B=t.toString,y=m();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(v.platform=y,define(function(){return y})):z&&
n?h(y,function(g,r){z[r]=g}):v.platform=y}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],c=0;c<a.length;c++){var b=document.createElement("meta");b.name=a[c].name;b.content=a[c].content;var h=window.document.head.querySelector('meta[name="'+b.name+'"]');h&&h.parentNode.removeChild(h);window.document.head.appendChild(b)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);console.log(window.devicePixelRatio);console.log(window.innerWidth);console.log(window.innerHeight);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();
break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;case 808:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}
function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}function isIOSLessThen13(){var a=platform.os,c=a.family.toLowerCase();a=parseFloat(a.version);return"ios"===c&&13>a?!0:!1}$(document).ready(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&"safari"===platform.name.toLowerCase()&&isIOSLessThen13()&&!iosInIframe()&&iosResize()});
!function(){var a="undefined"!=typeof window&&void 0!==window.document?window.document:{},c="undefined"!=typeof module&&module.exports,b=function(){for(var f,e=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],d=0,m=e.length,n={};d<m;d++)if((f=e[d])&&f[1]in a){for(d=0;d<f.length;d++)n[e[0][d]]=f[d];return n}return!1}(),h={change:b.fullscreenchange,error:b.fullscreenerror},p={request:function(f){return new Promise(function(e,d){var m=function(){this.off("change",
m);e()}.bind(this);this.on("change",m);f=f||a.documentElement;Promise.resolve(f[b.requestFullscreen]())["catch"](d)}.bind(this))},exit:function(){return new Promise(function(f,e){if(this.isFullscreen){var d=function(){this.off("change",d);f()}.bind(this);this.on("change",d);Promise.resolve(a[b.exitFullscreen]())["catch"](e)}else f()}.bind(this))},toggle:function(f){return this.isFullscreen?this.exit():this.request(f)},onchange:function(f){this.on("change",f)},onerror:function(f){this.on("error",f)},
on:function(f,e){var d=h[f];d&&a.addEventListener(d,e,!1)},off:function(f,e){var d=h[f];d&&a.removeEventListener(d,e,!1)},raw:b};b?(Object.defineProperties(p,{isFullscreen:{get:function(){return!!a[b.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[b.fullscreenElement]}},isEnabled:{enumerable:!0,get:function(){return!!a[b.fullscreenEnabled]}}}),c?module.exports=p:window.screenfull=p):c?module.exports={isEnabled:!1}:window.screenfull={isEnabled:!1}}();
var s_iScaleFactor=1,s_bIsIphone=!1,s_iOffsetX,s_iOffsetY,s_bFocus=!0;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}function isIpad(){var a=-1!==navigator.userAgent.toLowerCase().indexOf("ipad");return!a&&navigator.userAgent.match(/Mac/)&&navigator.maxTouchPoints&&2<navigator.maxTouchPoints?!0:a}function isMobile(){return isIpad()?!0:jQuery.browser.mobile}
function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");if(-1!==navigator.userAgent.toLowerCase().indexOf("iphone"))return s_bIsIphone=!0;for(;a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function getSize(a){var c=a.toLowerCase(),b=window.document,h=b.documentElement;if(void 0===window["inner"+a])a=h["client"+a];else if(window["inner"+a]!=h["client"+a]){var p=b.createElement("body");p.id="vpw-test-b";p.style.cssText="overflow:scroll";var f=b.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+c+":"+h["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";p.appendChild(f);h.insertBefore(p,b.head);
a=7==f["offset"+a]?h["client"+a]:window["inner"+a];h.removeChild(p)}else a=window["inner"+a];return a}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=null!==platform.name&&"safari"===platform.name.toLowerCase()?getIOSWindowHeight():getSize("Height");var c=getSize("Width");s_bFocus&&_checkOrientation(c,a);var b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),h=Math.round(CANVAS_WIDTH*b);b=Math.round(CANVAS_HEIGHT*b);if(b<a){var p=a-b;b+=p;h+=CANVAS_WIDTH/CANVAS_HEIGHT*p}else h<c&&(p=c-h,h+=p,b+=CANVAS_HEIGHT/CANVAS_WIDTH*p);p=a/2-b/2;var f=c/2-h/2,e=CANVAS_WIDTH/h;if(f*e<-EDGEBOARD_X||
p*e<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*EDGEBOARD_X)),h=Math.round(CANVAS_WIDTH*b),b=Math.round(CANVAS_HEIGHT*b),p=(a-b)/2,f=(c-h)/2,e=CANVAS_WIDTH/h;s_iOffsetX=-1*f*e;s_iOffsetY=-1*p*e;0<=p&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos();null!==s_oMenu&&s_oMenu.refreshButtonPos();null!==s_oModeMenu&&s_oModeMenu.refreshButtonPos();s_bIsIphone&&s_oStage?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*
h,s_oStage.canvas.height=2*b,canvas.style.width=h+"px",canvas.style.height=b+"px",s_oStage.scaleX=s_oStage.scaleY=2*Math.min(h/CANVAS_WIDTH,b/CANVAS_HEIGHT)):s_bMobile||isChrome()?($("#canvas").css("width",h+"px"),$("#canvas").css("height",b+"px")):s_oStage&&(s_oStage.canvas.width=h,s_oStage.canvas.height=b,s_iScaleFactor=Math.min(h/CANVAS_WIDTH,b/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>p||(p=(a-b)/2);$("#canvas").css("top",p+"px");$("#canvas").css("left",f+"px");fullscreenHandler()}}
function _checkOrientation(a,c){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>c?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,c,b){var h=new createjs.Bitmap(a),p=new createjs.Shape;c&&b?p.graphics.beginFill("#fff").drawRect(0,0,c,b):p.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);h.hitArea=p;return h}function createSprite(a,c,b,h,p,f){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-h,p,f);a.hitArea=c;return a}
(function(){function a(b){var h={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in h?document.body.className=h[b.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?(s_oMain.stopUpdate(),s_bFocus=!1):(s_oMain.startUpdate(),s_bFocus=!0))}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",
a):(c="webkitHidden")in document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();function saveItem(a,c){s_bStorageAvailable&&localStorage.setItem(a,c)}function getItem(a){return s_bStorageAvailable?localStorage.getItem(a):null}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,h;0!==c;)h=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[h],a[h]=b;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="";b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var c=Array.prototype.slice.call(arguments);return a.sort(function(b,h){for(var p=c.slice(),f=p.shift();b[f]==h[f]&&p.length;)f=p.shift();return b[f]==h[f]?0:b[f]>h[f]?1:-1})};function roundDecimal(a,c){var b=Math.pow(10,c);return Math.round(b*a)/b}function tweenVectors(a,c,b,h){h.set(a.getX()+b*(c.getX()-a.getX()),a.getY()+b*(c.getY()-a.getY()));return h}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};function playSound(a,c,b){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(c),s_aSounds[a].loop(b),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}
function setVolume(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(c)}function setMute(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(c)}function getParamValue(a){for(var c=window.location.search.substring(1).split("&"),b=0;b<c.length;b++){var h=c[b].split("=");if(h[0]==a)return h[1]}}
function fullscreenHandler(){ENABLE_FULLSCREEN&&!1!==screenfull.isEnabled&&(s_bFullscreen=screenfull.isFullscreen,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut(),null!==s_oModeMenu&&s_oModeMenu.resetFullscreenBut())}if(screenfull.isEnabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut();null!==s_oModeMenu&&s_oModeMenu.resetFullscreenBut()});
var s_szGameID="952cf64a1e0c4e2e8c2447227589e460";window.GD_OPTIONS={gameId:s_szGameID,onEvent:function(a){switch(a.name){case "SDK_GAME_START":s_oMain&&s_oMain.startUpdate();break;case "SDK_GAME_PAUSE":s_oMain&&s_oMain.stopUpdate()}}};(function(a,c,b){var h=a.getElementsByTagName(c)[0];a.getElementById(b)||(a=a.createElement(c),a.id=b,a.src="/main.min.js",h.parentNode.insertBefore(a,h))})(document,"script","gamedistribution-jssdk");
function CSpriteLibrary(){var a={},c,b,h,p,f,e;this.init=function(d,m,n){c={};h=b=0;p=d;f=m;e=n};this.addSprite=function(d,m){if(a.hasOwnProperty(d))return!1;var n=new Image;a[d]=c[d]={szPath:m,oSprite:n,bLoaded:!1};b++;return!0};this.getSprite=function(d){return a.hasOwnProperty(d)?a[d].oSprite:null};this._onSpritesLoaded=function(){b=0;f.call(e)};this._onSpriteLoaded=function(){p.call(e);++h===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var d in c)c[d].oSprite.oSpriteLibrary=this,
c[d].oSprite.szKey=d,c[d].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[d].oSprite.onerror=function(m){var n=m.currentTarget;setTimeout(function(){c[n.szKey].oSprite.src=c[n.szKey].szPath},500)},c[d].oSprite.src=c[d].szPath};this.setLoaded=function(d){a[d].bLoaded=!0};this.isLoaded=function(d){return a[d].bLoaded};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1360,CANVAS_HEIGHT=768,DISABLE_SOUND_MOBILE=!1,EDGEBOARD_X=210,EDGEBOARD_Y=84,FONT_GAME="Montserrat",STATE_LOADING=0,STATE_MENU=1,STATE_MODE_MENU=2,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_RELEASE_NO=6,ON_RELEASE_YES=7,ON_SELECT_LANG=8,TOTAL_SCENES=5,BALL_SIZE=73,BALL_ROTATION_SPEED=3,CAM_DISTANCE=1,PLAYER_HEIGHT=768,PLAYER_WIDTH=408,CART_HEIGHT=329,CART_WIDTH=356,SHOTGUI_SIZE=229,SHOTBALL_SIZE=48,CART_DEPTH_INDEX,
ERROR_MULT,TIME_AVAILABLE,NUM_SHOT_PER_SCENE=5,SELECTOR_SPEED,POINT_FOR_BALL,POINT_FOR_SPECIAL_BALL,NUM_LANGUAGES=7,LANG_EN=0,LANG_ES=1,LANG_FR=2,LANG_DE=3,LANG_PT=4,LANG_IT=5,LANG_RU=6,LANG_CODES={};LANG_CODES.en=LANG_EN;LANG_CODES.es=LANG_ES;LANG_CODES.fr=LANG_FR;LANG_CODES.de=LANG_DE;LANG_CODES.pt=LANG_PT;LANG_CODES.it=LANG_IT;LANG_CODES.ru=LANG_RU;var SOUNDTRACK_VOLUME_IN_GAME=.1,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION;
function CPreloader(){var a,c,b,h,p,f,e,d,m;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.png");s_oSpriteLibrary.loadSprites();m=new createjs.Container;s_oStage.addChild(m)};this.unload=function(){m.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var n=new createjs.Shape;n.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.addChild(n);n=s_oSpriteLibrary.getSprite("200x200");e=createBitmap(n);e.regX=.5*n.width;e.regY=.5*n.height;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-180;m.addChild(e);d=new createjs.Shape;d.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(e.x-100,e.y-100,200,200,10);m.addChild(d);e.mask=d;n=s_oSpriteLibrary.getSprite("progress_bar");h=createBitmap(n);h.x=CANVAS_WIDTH/2-
n.width/2;h.y=CANVAS_HEIGHT/2+50;m.addChild(h);a=n.width;c=n.height;p=new createjs.Shape;p.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(h.x,h.y,1,c);m.addChild(p);h.mask=p;b=new createjs.Text("","30px "+FONT_GAME,"#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT/2+100;b.textBaseline="alphabetic";b.textAlign="center";m.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);m.addChild(f);createjs.Tween.get(f).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(f);
m.removeChild(f)})};this.refreshLoader=function(n){b.text=n+"%";100===n&&(s_oMain._onRemovePreloader(),b.visible=!1,h.visible=!1);p.graphics.clear();n=Math.floor(n*a/100);p.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(h.x,h.y,n,c)};this._init()}
function CMain(a){ERROR_MULT=a.errorMultiplier;TIME_AVAILABLE=a.timeAvailable;SELECTOR_SPEED=a.selectorSpeed;POINT_FOR_BALL=a.point_per_ball;POINT_FOR_SPECIAL_BALL=a.point_per_special_ball;var c=!1,b=0,h=0,p=STATE_LOADING,f,e;this.initContainer=function(){s_oStage=new createjs.Stage("canvas");s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage,!0);s_bMobile=isMobile();!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.framerate=30;createjs.Ticker.addEventListener("tick",
this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader;c=!0};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/h*100))};this._initSounds=function(){Howler.mute(!s_bAudioActive);s_aSoundsInfo=[];s_aSoundsInfo.push({path:"./sounds/",filename:"bounce",loop:!1,volume:1,ingamename:"bounce"});s_aSoundsInfo.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});s_aSoundsInfo.push({path:"./sounds/",
filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});s_aSoundsInfo.push({path:"./sounds/",filename:"score_sfx",loop:!1,volume:1,ingamename:"score_sfx"});s_aSoundsInfo.push({path:"./sounds/",filename:"ambience",loop:!0,volume:1,ingamename:"ambience"});s_aSoundsInfo.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});s_aSoundsInfo.push({path:"./sounds/",filename:"hit_the_ring",loop:!1,volume:1,ingamename:"hit_the_ring"});s_aSoundsInfo.push({path:"./sounds/",
filename:"net",loop:!1,volume:1,ingamename:"net"});h+=s_aSoundsInfo.length;s_aSounds=[];for(var d=0;d<s_aSoundsInfo.length;d++)this.tryToLoadSound(s_aSoundsInfo[d],!1)};this.tryToLoadSound=function(d,m){setTimeout(function(){s_aSounds[d.ingamename]=new Howl({src:[d.path+d.filename+".mp3"],autoplay:!1,preload:!0,loop:d.loop,volume:d.volume,onload:s_oMain.soundLoaded,onloaderror:function(n,v){for(var z=0;z<s_aSoundsInfo.length;z++)if(n===s_aSounds[s_aSoundsInfo[z].ingamename]._sounds[0]._id){s_oMain.tryToLoadSound(s_aSoundsInfo[z],
!0);break}},onplayerror:function(n){for(var v=0;v<s_aSoundsInfo.length;v++)if(n===s_aSounds[s_aSoundsInfo[v].ingamename]._sounds[0]._id){s_aSounds[s_aSoundsInfo[v].ingamename].once("unlock",function(){s_aSounds[s_aSoundsInfo[v].ingamename].play();"soundtrack"===s_aSoundsInfo[v].ingamename&&null!==s_oGame&&setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME)});break}}})},m?200:0)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("ball_1","./sprites/ball_1.png");s_oSpriteLibrary.addSprite("ball_2","./sprites/ball_2.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("cart_back","./sprites/cart_back.png");s_oSpriteLibrary.addSprite("cart_front",
"./sprites/cart_front.png");s_oSpriteLibrary.addSprite("field_camera_1","./sprites/field_camera_1.jpg");s_oSpriteLibrary.addSprite("field_camera_2","./sprites/field_camera_2.jpg");s_oSpriteLibrary.addSprite("field_camera_3","./sprites/field_camera_3.jpg");s_oSpriteLibrary.addSprite("bg_selection","./sprites/bg_selection.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("shot_ball","./sprites/shot_ball.png");s_oSpriteLibrary.addSprite("shot_gui","./sprites/shot_gui.png");
s_oSpriteLibrary.addSprite("time_panel","./sprites/time_panel.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow.png");s_oSpriteLibrary.addSprite("logo_credits","./sprites/logo_credits.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("player_selection_0","./sprites/player_selection_0.png");s_oSpriteLibrary.addSprite("player_selection_1","./sprites/player_selection_1.png");
s_oSpriteLibrary.addSprite("player_selection_2","./sprites/player_selection_2.png");s_oSpriteLibrary.addSprite("but_next","./sprites/but_next.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("choose_player_text_0","./sprites/choose_player_text_0.png");s_oSpriteLibrary.addSprite("choose_player_text_1","./sprites/choose_player_text_1.png");s_oSpriteLibrary.addSprite("choose_player_text_2","./sprites/choose_player_text_2.png");
s_oSpriteLibrary.addSprite("choose_player_text_3","./sprites/choose_player_text_3.png");s_oSpriteLibrary.addSprite("choose_player_text_4","./sprites/choose_player_text_4.png");s_oSpriteLibrary.addSprite("choose_player_text_5","./sprites/choose_player_text_5.png");s_oSpriteLibrary.addSprite("choose_player_text_6","./sprites/choose_player_text_6.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart",
"./sprites/but_restart.png");s_oSpriteLibrary.addSprite("bg_best","./sprites/bg_best.png");s_oSpriteLibrary.addSprite("players","./sprites/players.png");s_oSpriteLibrary.addSprite("but_lang","./sprites/but_lang.png");for(var d=0;132>d;d++)s_oSpriteLibrary.addSprite("player_0_"+d,"./sprites/player_0/player_0_"+d+".png"),s_oSpriteLibrary.addSprite("player_1_"+d,"./sprites/player_1/player_1_"+d+".png"),s_oSpriteLibrary.addSprite("player_2_"+d,"./sprites/player_2/player_2_"+d+".png");for(d=1;36>=d;d++)s_oSpriteLibrary.addSprite("bsk"+
d,"./sprites/basket/basket_0"+(9>=d?"00"+d:99>=d?"0"+d:d)+".png");h+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/h*100))};this._onAllImagesLoaded=function(){};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this._onRemovePreloader=function(){try{checkMoreGames(s_szGameID,"bottom-left",["sport","multiplayer"],[],-1,"dark_yellow")}catch(d){}f.unload();
try{localStorage.setItem("ls_available","ok"),s_iBestScore=getItem("street_basket_score_gd"),null===s_iBestScore&&(s_iBestScore=0)}catch(d){s_bStorageAvailable=!1}s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){try{showMoreGames()}catch(d){}new CMenu;p=STATE_MENU};this.gotoModeMenu=function(){new CMenuMode;p=STATE_MODE_MENU};this.gotoGame=function(){e=new CGame;p=STATE_GAME};this.gotoHelp=function(){_oHelp=new CHelp;p=STATE_HELP};this.stopUpdate=function(){c=!1;
createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();c=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(d){if(c){var m=(new Date).getTime();s_iTimeElaps=m-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=m;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,
s_iCntTime-=1E3,s_iCntFps=0);p===STATE_GAME&&e.update(m);s_oStage.update(d)}};s_oMain=this;ENABLE_FULLSCREEN=a.fullscreen;ENABLE_CHECK_ORIENTATION=a.check_orientation;s_bAudioActive=a.audio_enable_on_startup;a=navigator.language.split("-")[0];void 0===LANG_CODES[a]&&(a="en");s_iCurLang=LANG_CODES[a];refreshLanguage();this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings,s_oSoundTrack=null,s_bFullscreen=!1,s_aSounds,s_aSoundsInfo,s_iPlayerSelected=0,s_iBestScore=0,s_bStorageAvailable=!0,s_iCurLang=LANG_EN;
function CTextButton(a,c,b,h,p,f,e,d){var m,n,v,z,t,w,u,q,B,y;this._init=function(g,r,x,A,C,I,k){m=!1;n=1;v=[];z=[];y=createBitmap(x);q=new createjs.Container;q.x=g;q.y=r;q.regX=x.width/2;q.regY=x.height/2;s_bMobile||(q.cursor="pointer");q.addChild(y,B);d.addChild(q);B=new CTLText(q,30,25,x.width-60,x.height-50,k,"center",I,C,1.1,0,0,A,!0,!0,!1,!1);this._initListener()};this.unload=function(){q.off("mousedown",t);q.off("pressup",w);d.removeChild(q)};this.setVisible=function(g){q.visible=g};this.setAlign=
function(g){B.textAlign=g};this.setTextX=function(g){B.x=g};this.setScale=function(g){n=q.scaleX=q.scaleY=g};this.enable=function(){m=!1};this.disable=function(){m=!0};this._initListener=function(){t=q.on("mousedown",this.buttonDown);w=q.on("pressup",this.buttonRelease)};this.addEventListener=function(g,r,x){v[g]=r;z[g]=x};this.addEventListenerWithParams=function(g,r,x,A){v[g]=r;z[g]=x;u=A};this.buttonRelease=function(){m||(playSound("click",1,!1),q.scaleX=n,q.scaleY=n,v[ON_MOUSE_UP]&&v[ON_MOUSE_UP].call(z[ON_MOUSE_UP],
u))};this.buttonDown=function(){m||(q.scaleX=.9*n,q.scaleY=.9*n,v[ON_MOUSE_DOWN]&&v[ON_MOUSE_DOWN].call(z[ON_MOUSE_DOWN]))};this.setPosition=function(g,r){q.x=g;q.y=r};this.tweenPosition=function(g,r,x,A,C,I,k){createjs.Tween.get(q).wait(A).to({x:g,y:r},x,C).call(function(){void 0!==I&&I.call(k)})};this.changeText=function(g){B.refreshText(g)};this.setX=function(g){q.x=g};this.setY=function(g){q.y=g};this.getButtonImage=function(){return q};this.getX=function(){return q.x};this.getY=function(){return q.y};
this.getSprite=function(){return q};this.getScale=function(){return q.scaleX};this._init(a,c,b,h,p,f,e)}
function CGfxButton(a,c,b,h){var p,f,e,d,m,n=[],v,z,t;this._init=function(w,u,q){p=!1;d=[];m=[];f=q.width;e=q.height;t=createBitmap(q);t.x=w;t.y=u;t.regX=q.width/2;t.regY=q.height/2;s_bMobile||(t.cursor="pointer");h.addChild(t);this._initListener()};this.unload=function(){t.off("mousedown",v);t.off("pressup",z);h.removeChild(t)};this.setVisible=function(w){t.visible=w};this._initListener=function(){v=t.on("mousedown",this.buttonDown);z=t.on("pressup",this.buttonRelease)};this.addEventListener=function(w,
u,q){d[w]=u;m[w]=q};this.addEventListenerWithParams=function(w,u,q,B){d[w]=u;m[w]=q;n=B};this.buttonRelease=function(){p||(playSound("click",1,!1),t.scaleX=1,t.scaleY=1,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(m[ON_MOUSE_UP],n))};this.buttonDown=function(){p||(t.scaleX=.9,t.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN],n))};this.setPosition=function(w,u){t.x=w;t.y=u};this.setX=function(w){t.x=w};this.setY=function(w){t.y=w};this.enable=function(){p=!1;t.filters=[];t.cache(0,0,f,e)};
this.disable=function(){p=!0;var w=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);t.filters=[new createjs.ColorMatrixFilter(w)];t.cache(0,0,f,e)};this.getButtonImage=function(){return t};this.getX=function(){return t.x};this.getY=function(){return t.y};this._init(a,c,b);return this}
function CToggle(a,c,b,h,p){var f,e,d,m,n,v,z;this._init=function(w,u,q,B){e=[];d=[];var y=new createjs.SpriteSheet({images:[q],frames:{width:q.width/2,height:q.height,regX:q.width/2/2,regY:q.height/2},animations:{state_true:[0],state_false:[1]}});f=B;z=createSprite(y,"state_"+f,q.width/2/2,q.height/2,q.width/2,q.height);z.x=w;z.y=u;z.stop();t.addChild(z);this._initListener()};this.unload=function(){z.off("mousedown",m);z.off("pressup",n);s_bMobile||z.off("mouseover",v);t.removeChild(z)};this._initListener=
function(){m=z.on("mousedown",this.buttonDown);n=z.on("pressup",this.buttonRelease);s_bMobile||(v=z.on("mouseover",this.buttonOver))};this.addEventListener=function(w,u,q){e[w]=u;d[w]=q};this.setActive=function(w){f=w;z.gotoAndStop("state_"+f)};this.buttonRelease=function(){z.scaleX=1;z.scaleY=1;playSound("click",1,!1);f=!f;z.gotoAndStop("state_"+f);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(d[ON_MOUSE_UP],f)};this.buttonDown=function(){z.scaleX=.9;z.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN])};
this.buttonOver=function(w){s_bMobile||(w.target.cursor="pointer")};this.setPosition=function(w,u){z.x=w;z.y=u};var t=p;this._init(a,c,b,h)}
function CMenu(){var a,c,b,h,p,f,e,d,m,n,v,z,t,w,u=null,q=null,B;this._init=function(){m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(m);var y=s_oSpriteLibrary.getSprite("but_play");v=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+120,y,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onButPlay,this,!1);var g=s_oSpriteLibrary.getSprite("but_lang");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(y=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-y.width/4-10,d=y.height/2+10,
z=new CToggle(e,d,y,s_bAudioActive,s_oStage),z.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),a=e-g.width/NUM_LANGUAGES-10,c=d):(a=CANVAS_WIDTH-y.width/4-10,c=y.height/2+10);n=new CButLang(a,c,NUM_LANGUAGES,s_iCurLang,g,s_oStage);n.addEventListener(ON_SELECT_LANG,this._onChangeLang,this);y=s_oSpriteLibrary.getSprite("but_credits");p=y.height/2+10;f=y.height/2+10;t=new CGfxButton(p,f,y,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onCredits,this);y=window.document;g=y.documentElement;u=g.requestFullscreen||
g.mozRequestFullScreen||g.webkitRequestFullScreen||g.msRequestFullscreen;q=y.exitFullscreen||y.mozCancelFullScreen||y.webkitExitFullscreen||y.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(u=!1);u&&screenfull.isEnabled&&(y=s_oSpriteLibrary.getSprite("but_fullscreen"),b=p+y.width/2+10,h=f,w=new CToggle(b,h,y,s_bFullscreen,s_oStage),w.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));y=s_oSpriteLibrary.getSprite("logo_menu");g=createBitmap(y);g.regX=y.width/2;g.regY=y.height/2;g.x=CANVAS_WIDTH/
2;g.y=-y.height/2;s_oStage.addChild(g);s_bStorageAvailable||new CAlertSavingBox(TEXT_ERR_LS,s_oStage);B=new createjs.Shape;B.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(B);createjs.Tween.get(B).to({alpha:0},1E3).call(function(){B.visible=!1});createjs.Tween.get(g).wait(500).to({y:CANVAS_HEIGHT/2-140},500,createjs.Ease.backOut);this.refreshButtonPos();setVolume("soundtrack",1)};this.refreshButtonPos=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||z.setPosition(e-
s_iOffsetX,s_iOffsetY+d);u&&screenfull.isEnabled&&w.setPosition(b+s_iOffsetX,h+s_iOffsetY);t.setPosition(p+s_iOffsetX,s_iOffsetY+f);n.setPosition(a-s_iOffsetX,c+s_iOffsetY)};this.unload=function(){v.unload();v=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z.unload(),z=null;u&&screenfull.isEnabled&&w.unload();n.unload();s_oStage.removeAllChildren();s_oMenu=null};this.resetFullscreenBut=function(){u&&screenfull.isEnabled&&w.setActive(s_bFullscreen)};this._onChangeLang=function(y){s_iCurLang=y;refreshLanguage()};
this._onCredits=function(){new CCreditsPanel};this._onButPlay=function(){"undefined"!==typeof gdsdk&&"undefined"!==gdsdk.showAd&&gdsdk.showAd();try{hideMoreGames()}catch(y){}this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoModeMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onFullscreenRelease=function(){s_bFullscreen?q.call(window.document):u.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}
var s_oMenu=null;
function CHelpPanel(){var a=!0,c,b,h,p,f;this._init=function(){p=new createjs.Container;p.visible=!1;c=p.on("click",this._onExit,this);s_oStage.addChild(p);b=new createjs.Shape;b.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);b.alpha=0;p.addChild(b);f=new createjs.Container;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;p.addChild(f);var e=s_oSpriteLibrary.getSprite("bg_help");h=createBitmap(e);f.addChild(h);(new CTLText(f,20,20,e.width-40,130,48,"center","#fba500",FONT_GAME,1,0,0,s_bMobile?
TEXT_HELP_MOBILE:TEXT_HELP,!0,!0,!0,!1)).setShadow("#000",2,2,2);(new CTLText(f,36,305,130,28,28,"center","#fba500",FONT_GAME,1,0,0,POINT_FOR_BALL+" "+TEXT_POINT,!0,!0,!1,!1)).setShadow("#000",2,2,2);(new CTLText(f,186,305,130,28,28,"center","#fba500",FONT_GAME,1,0,0,POINT_FOR_SPECIAL_BALL+" "+TEXT_POINTS,!0,!0,!1,!1)).setShadow("#000",2,2,2);f.regX=f.getBounds().width/2;f.regY=f.getBounds().height/2};this.show=function(e){a=e;f.scale=.01;p.visible=!0;createjs.Tween.get(b).to({alpha:.8},500,createjs.Ease.cubicOut);
createjs.Tween.get(f).wait(250).to({scale:.95},500,createjs.Ease.backOut)};this.hide=function(){createjs.Tween.get(b).wait(250).to({alpha:0},500,createjs.Ease.cubicOut);createjs.Tween.get(f).to({scale:.01},500,createjs.Ease.backIn).call(function(){p.visible=!1})};this.unload=function(){p.off("click",c);p.removeAllChildren()};this._onExit=function(){s_oGame.exitFromHelp(a)};this._init()}
function CGame(){var a=!1,c=!1,b=!1,h=!0,p=!1,f=!1,e,d,m,n=0,v=0,z=0,t,w,u=[],q,B,y,g=null,r,x,A,C,I;this._init=function(){e=0;d=1;m=NUM_SHOT_PER_SCENE;w=TIME_AVAILABLE;q=new CANNON.World;q.gravity.set(0,0,-400);q.broadphase=new CANNON.NaiveBroadphase;q.solver.iterations=5;A=new CANNON.Material;C=new CANNON.Material;I=new CANNON.Material;var k=new CANNON.ContactMaterial(A,A,{friction:.2,restitution:.55}),G=new CANNON.ContactMaterial(C,A,{friction:.05,restitution:.35}),R=new CANNON.ContactMaterial(C,
I,{friction:.25,restitution:.5});q.addContactMaterial(k);q.addContactMaterial(G);q.addContactMaterial(R);k=new CANNON.Plane;G=new CANNON.Body({mass:0,material:A});G.addShape(k);q.add(G);x=new CSceneStatic(q,d,A,I);k=x.getCartCoords();r=new CPlayer(this,k);for(G=0;G<m;G++)u.push(new CBall(q,A,A,d,G,k));B=new CInterface(this);y=new CHelpPanel;y.show(!0);setVolume("soundtrack",SOUNDTRACK_VOLUME_IN_GAME);playSound("ambience",1,!0);$(s_oMain).trigger("start_level",1)};this.unload=function(){$(s_oMain).trigger("end_session");
0<n&&$(s_oMain).trigger("share_event",n);stopSound("ambience");for(var k=q.bodies.length,G=0;G<k;G++)q.remove(q.bodies[0]);q=null;createjs.Tween.removeAllTweens();s_oStage.removeAllEventListeners();s_oStage.removeAllChildren();B.unload();y.unload();null!==g&&g.unload();s_oMain.gotoMenu()};this.exitFromHelp=function(k){y.hide();k&&(e=1)};this._onInfo=function(){y.show(!1)};this.getState=function(){return _oGameStates[void 0]};this.ballWaitToThrow=function(){0<m&&u[m-1].waitToThrow()};this.updateLanguageText=
function(){B.updateShots(v);B.updateTime(w);B.updateScore(n)};this.update=function(k){1<e&&(void 0===t?t=k:(w=Math.floor(TIME_AVAILABLE-(k-t)),0<=w?B.updateTime(w):(playSound("game_over",1,!1),g=new CEndPanel(w,n,v,this),e=-1)));1===e&&(z++,r.idle1(),30<z&&(e=2));if(2===e){B.listenForClick();r.grab1();if(r.isBallGrabbed()&&!b)for(b=!0,u[m-1].grab(r.getPlCoords()),k=0;k<m-1;k++)u[k].slide();B.isVectorAquired().state&&(e=3)}3===e&&(a||(a=!0,u[m-1].throwingBall(r.getPlCoords(),B.isVectorAquired().vector,
u[m-1]),u[m-1].update()),r.throwing(d)&&(e=4,h=!0,f=p=a=!1));if(4===e){h&&(b=h=!1,r.newBall(),x.newBall(),m--,v++,B.updateShots(v));u[m].update();k=x.updateBasket(u[m].getPosition());!0===k?(p=!0,k=x.getBasketPos(d),0===u[m].getCartPosition()?(n+=POINT_FOR_SPECIAL_BALL,new CScoreTextAnim("+"+POINT_FOR_SPECIAL_BALL,k.x,k.y,"#fba500",s_oStage)):(n+=POINT_FOR_BALL,new CScoreTextAnim("+"+POINT_FOR_BALL,k.x,k.y,"#fba500",s_oStage)),B.updateScore(n),playSound("score_sfx",1,!1)):!1===k&&!1===p&&(f=!0);!0===
p?(p=x.scored(),f=!1):f&&(f=x.rimCollision());u[m].touchGround();if(0<m){if(r.grab2(),r.isBallGrabbed()&&!b)for(b=!0,u[m-1].grab(r.getPlCoords()),k=0;k<m-1;k++)u[k].slide()}else r.endTurn();u[m].touchedGround()&&(c||(B.newBall(),c=!0),0<m?(B.listenForClick(),B.isVectorAquired().state&&(e=3,c=!1)):0===m&&(c=!1,e=5))}if(5===e)if(d++,5>=d){m=NUM_SHOT_PER_SCENE;r.endTurn();x.nextScene();r.nextScene(x.getCartCoords());for(k=0;k<m;k++)u[k].unload(),u[k]=new CBall(q,A,A,d,k,x.getCartCoords());e=1}else g=
new CEndPanel(w,n,v,this),e=-1};s_oGame=this;this._init()}var s_oGame;
function CBall(a,c,b,h,p,f){var e=[[-1.324419465111331,.07007920010441403,.1938814229049522,.1928501356834461,-.2649754991389736,-.29199768911624474,-.9738954395935614,-.9687151293457442,.00813866187260608,1.8973661726282403,-.15703993365948804,-.1562046123872247,172.14460555118495,-57.92280926049329,268.64013255353115,275.1899143092173],[-1.0311847252524577,-.17599844916970192,-.6427545415461143,-.6393356242752912,.8719967238119737,-.26330126009450605,-.7552979557156582,-.7512804014885001,.025392432048756682,
1.8946950915444967,-.16466751447142178,-.16379162084052554,74.75179565415395,-37.2124724898568,323.023333753347,329.2838423047125],[-.04192064711782405,-.28804391554765474,-.9934914290013894,-.9882068844583713,1.3500256223076117,-.017671886269370676,-.030155903522676906,-.02999549930503738,.006203995474932445,1.8991816460801592,-.15096085318711913,-.15015786754513807,6.84660099873786,-40.15800737796026,335.8181997013088,342.0106502533296],[1.0287322954933102,-.20296283656350578,-.6427545605150148,
-.6393356431432929,.8752566449130996,.2404296293623392,.7552979421456383,.7512803879906613,-8.671184282911734E-4,1.895038730402846,-.1646675026722602,-.16379160910412566,-75.22073485514608,-35.249324074836075,323.0233348288672,329.2838433745118],[1.3232711036898168,-.00901517234163781,.201487851298251,.20041610423131065,-.2666922478682122,.28881907281462693,.9738954354986644,.9687151252726287,.04684016896142928,1.8991247445227672,-.14715365255419113,-.14637091803943836,-176.51195787275645,-53.18780012690175,
267.37304986600344,273.9295714431983]],d=!1,m=!1,n=!1,v=!1,z=0,t=[0,new CANNON.Vec3(97,150,86),new CANNON.Vec3(178,80,86),new CANNON.Vec3(195,-26,86),new CANNON.Vec3(130,-110,86),new CANNON.Vec3(112,-150,87)],w=[0,new CANNON.Vec3(97,150,78.5),new CANNON.Vec3(178,80,78.5),new CANNON.Vec3(195,-26,78.5),new CANNON.Vec3(130,-110,78.5),new CANNON.Vec3(112,-150,79.5)],u=[0,new CANNON.Vec3(-1292.5,-5287.5,6697.5),new CANNON.Vec3(-3995,-2702.5,6697.5),new CANNON.Vec3(-4935,940,6580),new CANNON.Vec3(-2398.5,
4036.5,6552),new CANNON.Vec3(-1755,5206.5,6669)],q=f.x-BALL_SIZE;f=f.y-.4*CANVAS_HEIGHT;var B={x:0,y:0},y=0;this._oSphereBody;this._oStandBody;this._oSprite;this._oSpriteShadow;this._oContainer=void 0;this._v2SlideDestination={x:0,y:0};var g=new CANNON.Sphere(7);this._oSphereBody=new CANNON.Body({mass:1,material:c});this._oSphereBody.position.copy(t[h]);this._oSphereBody.addShape(g);c=new CANNON.Box(new CANNON.Vec3(2.5,2.5,.5));this._oStandBody=new CANNON.Body({mass:0,material:b});this._oStandBody.position.copy(w[h]);
this._oStandBody.addShape(c);this._oSpriteShadow=createBitmap(s_oSpriteLibrary.getSprite("shadow"));this._oSpriteShadow.regX=52;this._oSpriteShadow.regY=22;this._oSpriteShadow.visible=!1;this._oSprite=createBitmap(s_oSpriteLibrary.getSprite(0===p?"ball_2":"ball_1"));this._oSprite.regX=BALL_SIZE/2;this._oSprite.regY=BALL_SIZE/2;this._oSprite.x=5>h?q-p*BALL_SIZE*.75:q+(p-(NUM_SHOT_PER_SCENE-1))*BALL_SIZE*.75;this._oSprite.y=f;this._oContainer=new createjs.Container;this._oContainer.addChild(this._oSpriteShadow,
this._oSprite);s_oStage.addChildAt(this._oContainer,CART_DEPTH_INDEX+1);this.unload=function(){a.remove(this._oSphereBody);a.remove(this._oStandBody);s_oStage.removeChild(this._oContainer)};this.update=function(){if(!n){a.step(1/30);y=B.x;B=this._projCoordScaling(this._oSphereBody.position);var r=B.x-y,x=B.diam/BALL_SIZE;1<x&&(x=1);this._oSprite.x=B.x;this._oSprite.y=B.y;this._oSprite.scaleY=this._oSprite.scaleX=x;z+=r*BALL_ROTATION_SPEED;this._oSprite.rotation=z;this._oSpriteShadow.visible=!0;this._oSpriteShadow.x=
B.shadowX;this._oSpriteShadow.y=B.shadowY;this._oSpriteShadow.scaleX=this._oSpriteShadow.x.scaleY=.75*x;this._oSpriteShadow.alpha=this._oSprite.y/CANVAS_HEIGHT*.66+.33}};this.grab=function(r){d||(d=!0,createjs.Tween.removeTweens(this._oSprite),5>h?createjs.Tween.get(this._oSprite).to({x:r.x,y:r.y},80,createjs.Ease.cubicIn):createjs.Tween.get(this._oSprite).to({x:r.x+100,y:r.y},80,createjs.Ease.cubicIn))};this.slide=function(){z-=75;5>h?createjs.Tween.get(this._oSprite).to({x:this._oSprite.x-.8*BALL_SIZE,
rotation:z},500,createjs.Ease.linear):createjs.Tween.get(this._oSprite).to({x:this._oSprite.x+.8*BALL_SIZE,rotation:z},500,createjs.Ease.linear)};this.waitToThrow=function(){if(!m&&!n){m=!0;var r=this;createjs.Tween.get(this._oSprite).to({y:this._oSprite.y+7},450,createjs.Ease.linear).call(function(){createjs.Tween.get(r._oSprite).to({y:r._oSprite.y-7},450,createjs.Ease.linear).call(function(){m=!1})},r)}};this._projCoord=function(r){var x=r.x,A=r.y,C=x;r=r.z;var I=e[h-1],k=1/(I[3]*C+I[7]*A+I[11]*
r+I[15]);x=(I[0]*C+I[4]*A+I[8]*r+I[12])*k;A=(I[1]*C+I[5]*A+I[9]*r+I[13])*k;x=(x+1)*CANVAS_WIDTH/2;A=(-A+1)*CANVAS_HEIGHT/2;return{x:x,y:A}};this._projCoordScaling=function(r){var x=this._projCoord(new CANNON.Vec3(r.x,r.y,r.z+7)),A=this._projCoord(new CANNON.Vec3(r.x,r.y,r.z-7));r=this._projCoord(new CANNON.Vec3(r.x,r.y,0));return{x:(x.x+A.x)/2,y:(x.y+A.y)/2,diam:Math.abs(x.y-A.y),shadowX:r.x,shadowY:r.y}};this.throwingBall=function(r,x,A){var C,I,k=this;5>h?(C=r.x-40,I=r.y-172):(C=r.x+145,I=r.y-172);
n||(n=!0,createjs.Tween.removeTweens(this._oSprite),createjs.Tween.get(this._oSprite).to({x:C,y:I},100,createjs.Ease.linear).call(function(){var G;1===h?G=new CANNON.Vec3(u[1].x-x.x*ERROR_MULT,u[1].y+x.y*ERROR_MULT,u[1].z):2===h?G=new CANNON.Vec3(u[2].x-x.x*ERROR_MULT,u[2].y+x.y*ERROR_MULT,u[2].z):3===h?G=new CANNON.Vec3(u[3].x+x.y*ERROR_MULT,u[3].y+x.x*ERROR_MULT,u[3].z):4===h?G=new CANNON.Vec3(u[4].x+x.x*ERROR_MULT,u[4].y-x.y*ERROR_MULT,u[4].z):5===h&&(G=new CANNON.Vec3(u[5].x+x.x*ERROR_MULT,u[5].y-
x.y*ERROR_MULT,u[5].z));a.add(A._oSphereBody);a.add(A._oStandBody);k._oSphereBody.applyForce(G,k._oSphereBody.position)},k),k.update(),n=!1)};this.touchGround=function(){var r=this;7.01>=this._oSphereBody.position.z&&!1===v&&(playSound("bounce",1,!1),v=!0,createjs.Tween.get(r._oContainer).to({alpha:0},1E3,createjs.Ease.circIn).call(function(){r.unload()},r))};this.touchedGround=function(){return v};this.getPosition=function(){return this._oSphereBody.position};this.getCartPosition=function(){return p}}
function CInterface(a){var c,b,h,p,f,e,d,m,n,v,z,t,w,u,q,B,y=!0,g=!1,r=!1,x=!1,A=!1,C=!1,I=void 0,k=void 0,G=SHOTGUI_SIZE/3,R=.75*CANVAS_WIDTH,T=.45*CANVAS_HEIGHT,W,aa,O,M,U,P,X,l,Y,Z,S,J,D,H,N,E=null,ba=null;this.init=function(F){W=F;F=s_oSpriteLibrary.getSprite("shot_gui");U=createBitmap(F);U.regX=SHOTGUI_SIZE/2;U.regY=SHOTGUI_SIZE/2;U.x=R;U.y=T;s_oStage.addChild(U);p=h=10;H=new createjs.Container;H.x=h;s_oStage.addChild(H);F=s_oSpriteLibrary.getSprite("time_panel");P=createBitmap(F);H.addChild(P);
Z=new CTLText(H,P.x+8,15,F.width-16,24,24,"center","#fba500",FONT_GAME,1,0,0,TEXT_TIME_LEFT+" "+formatTime(TIME_AVAILABLE),!0,!0,!1,!1);Z.setShadow("#000000",3,3,4);J=new CTLText(H,P.x+8,46,F.width-16,30,30,"center","#fba500",FONT_GAME,1,0,0,TEXT_SCORE+" 0",!0,!0,!1,!1);J.setShadow("#000000",3,3,4);D=new CTLText(H,P.x+8,78,F.width-16,30,30,"center","#fba500",FONT_GAME,1,0,0,TEXT_SHOTS+" 0",!0,!0,!1,!1);D.setShadow("#000000",3,3,4);F=s_oSpriteLibrary.getSprite("bg_best");f=10;e=CANVAS_HEIGHT-F.height-
10;B=new createjs.Container;B.x=f;B.y=e;s_oStage.addChild(B);var K=createBitmap(F);B.addChild(K);S=new CTLText(B,8,7,F.width-16,F.height-10,30,"center","#fba500",FONT_GAME,1,0,0,TEXT_BEST+": "+s_iBestScore,!0,!0,!1,!1);O=createBitmap(s_oSpriteLibrary.getSprite("shot_ball"));O.regX=SHOTBALL_SIZE/2;O.regY=SHOTBALL_SIZE/2;O.x=R-100;O.y=T;s_oStage.addChild(O);M=createBitmap(s_oSpriteLibrary.getSprite("shot_ball"));M.regX=SHOTBALL_SIZE/2;M.regY=SHOTBALL_SIZE/2;M.x=R;M.y=T-100;M.visible=!1;s_oStage.addChild(M);
aa=new createjs.Shape;aa.graphics.beginFill("Black").drawRect(0,75,CANVAS_WIDTH,CANVAS_HEIGHT-75);aa.alpha=.01;s_oStage.addChild(aa);aa.on("mousedown",this._handleClick,this);F=window.document;K=F.documentElement;E=K.requestFullscreen||K.mozRequestFullScreen||K.webkitRequestFullScreen||K.msRequestFullscreen;ba=F.exitFullscreen||F.mozCancelFullScreen||F.webkitExitFullscreen||F.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(E=!1);F=s_oSpriteLibrary.getSprite("but_exit");n=CANVAS_WIDTH-F.width/2-10;v=F.height/
2+10;l=new CGfxButton(n,v,F,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onExit,this);c=n-F.width-10;b=v;Y=new CGfxButton(c,b,s_oSpriteLibrary.getSprite("but_credits"),s_oStage);Y.addEventListener(ON_MOUSE_UP,s_oGame._onInfo,s_oGame);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(F=s_oSpriteLibrary.getSprite("audio_icon"),d=c-F.width/2-10,m=v,X=new CToggle(d,m,F,s_bAudioActive,s_oStage),X.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),F=s_oSpriteLibrary.getSprite("but_fullscreen"),t={x:d-F.width/
2-10,y:v}):(F=s_oSpriteLibrary.getSprite("but_fullscreen"),t={x:c-F.width/2-10,y:v});K=s_oSpriteLibrary.getSprite("but_lang");E&&screenfull.isEnabled?(N=new CToggle(t.x,t.y,F,s_bFullscreen,s_oStage),N.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this),w={x:t.x-K.width/NUM_LANGUAGES-10,y:t.y}):w=t;q=new CButLang(w.x,w.y,NUM_LANGUAGES,s_iCurLang,K,s_oStage);q.addEventListener(ON_SELECT_LANG,this._onChangeLang,this);u=new CAreYouSurePanel(s_oStage);u.addEventListener(ON_RELEASE_NO,this._onHideConfirmPanel,
this);u.addEventListener(ON_RELEASE_YES,this._onConfirmExit,this);z=!1;!1===s_bMobile&&(document.onkeydown=this.onKeyDown,document.onkeyup=this.onKeyUp);this.refreshButtonPos()};this.refreshButtonPos=function(){l.setPosition(n-s_iOffsetX,s_iOffsetY+v);Y.setPosition(c-s_iOffsetX,s_iOffsetY+b);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||X.setPosition(d-s_iOffsetX,s_iOffsetY+m);E&&screenfull.isEnabled&&N.setPosition(t.x-s_iOffsetX,t.y+s_iOffsetY);q.setPosition(w.x-s_iOffsetX,w.y+s_iOffsetY);H.x=h+s_iOffsetX;
H.y=p+s_iOffsetY;B.x=f+s_iOffsetX;B.y=e-s_iOffsetY};this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||X.unload();E&&screenfull.isEnabled&&N.unload();Y.unload();l.unload();q.unload();document.onkeydown=null;s_oInterface=document.onkeyup=null};this.resetFullscreenBut=function(){E&&screenfull.isEnabled&&N.setActive(s_bFullscreen)};this.updateTime=function(F){F=TEXT_TIME_LEFT+" "+formatTime(F);Z.refreshText(F)};this.updateScore=function(F){J.refreshText(TEXT_SCORE+" "+F)};this.updateShots=
function(F){D.refreshText(TEXT_SHOTS+" "+F)};this._handleClick=function(F){if(!y){y=!1;if(!0===r)return r=!1,x=!0,I=Math.floor((O.x-R)/G*100)/100,M.visible=!0;!0===x&&(x=!1,k=Math.floor((M.y-T)/G*100)/100,g=!0)}};this.onKeyUp=function(F){z=!1};this.onKeyDown=function(F){if(!z){z=!0;F||(F=window.event);switch(F.keyCode){case 32:s_oInterface._handleClick()}F.preventDefault();return!1}};this.listenForClick=function(){y=!1;g||(!1===r&&!1===x&&(r=!0),this._animateShotBall());return!0};this._animateShotBall=
function(){r?A?(O.x-=SELECTOR_SPEED,O.x<R-G&&(A=!1)):(O.x+=SELECTOR_SPEED,O.x>R+G&&(A=!0)):x&&(C?(M.y-=SELECTOR_SPEED,M.y<.45*CANVAS_HEIGHT-G&&(C=!1)):(M.y+=SELECTOR_SPEED,M.y>.45*CANVAS_HEIGHT+G&&(C=!0)))};this.isVectorAquired=function(){return{state:g,vector:{x:I,y:k}}};this.newBall=function(){y=!0;C=A=x=r=g=!1;O.x=R-100;O.y=T;M.x=R;M.y=T-100;M.visible=!1};this._onChangeLang=function(F){s_iCurLang=F;refreshLanguage();s_oGame.updateLanguageText();S.refreshText(TEXT_BEST+": "+s_iBestScore)};this._onAudioToggle=
function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){u.show(TEXT_ARE_YOU_SURE)};this._onFullscreenRelease=function(){s_bFullscreen?ba.call(window.document):E.call(window.document.documentElement);sizeHandler()};this._onHideConfirmPanel=function(){u.hide()};this._onConfirmExit=function(){W.unload()};s_oInterface=this;this.init(a)}var s_oInterface=null;
function CSceneStatic(a,c,b,h){var p=!0,f=!0,e=!1,d=0,m=c,n=[],v=[{},{x:.648*CANVAS_WIDTH,y:.88*CANVAS_HEIGHT/5},{x:.504*CANVAS_WIDTH,y:.79*CANVAS_HEIGHT/5},{x:.484*CANVAS_WIDTH,y:.81*CANVAS_HEIGHT/5},{x:2.24/5*CANVAS_WIDTH,y:.79*CANVAS_HEIGHT/5},{x:.306*CANVAS_WIDTH,y:.88*CANVAS_HEIGHT/5}],z=[{},{x:1018,y:720},{x:868,y:720},{x:868,y:720},{x:868,y:720},{x:448,y:720}];var t=createBitmap(s_oSpriteLibrary.getSprite("field_camera_1"));t.scaleX=-1;t.x=CANVAS_WIDTH;s_oStage.addChild(t);var w=createBitmap(s_oSpriteLibrary.getSprite("cart_back"));
s_oStage.addChild(w);var u=createBitmap(s_oSpriteLibrary.getSprite("cart_front"));s_oStage.addChild(u);CART_DEPTH_INDEX=s_oStage.getChildIndex(w);w.regX=u.regX=CART_WIDTH/2;w.regY=u.regY=CART_HEIGHT/2;w.x=u.x=z[1].x;w.y=u.y=z[1].y;c=new CANNON.Box(new CANNON.Vec3(.5,36,21));b=new CANNON.Body({mass:0,position:new CANNON.Vec3(48,0,120),material:b});b.addShape(c);a.add(b);c=new CANNON.Box(new CANNON.Vec3(11,.5,.5));b=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,11,120),material:h});b.addShape(c);
a.add(b);var q=new CANNON.Box(new CANNON.Vec3(11,.5,.5));c=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,-11,120),material:h});c.addShape(q);a.add(c);q=new CANNON.Box(new CANNON.Vec3(.5,11,.5));var B=new CANNON.Body({mass:0,position:new CANNON.Vec3(70,0,120),material:h});B.addShape(q);a.add(B);b.addEventListener("collide",function(y){e=!0});c.addEventListener("collide",function(y){e=!0});B.addEventListener("collide",function(y){e=!0});b=new CANNON.Box(new CANNON.Vec3(8,.5,.5));c=new CANNON.Body({mass:0,
position:new CANNON.Vec3(59,8,113),material:h});c.addShape(b);a.add(c);b=new CANNON.Box(new CANNON.Vec3(8,.5,.5));c=new CANNON.Body({mass:0,position:new CANNON.Vec3(59,-8,113),material:h});c.addShape(b);a.add(c);b=new CANNON.Box(new CANNON.Vec3(.5,8,.5));h=new CANNON.Body({mass:0,position:new CANNON.Vec3(67,0,113),material:h});h.addShape(b);a.add(h);for(a=0;36>a;a++)n.push(createBitmap(s_oSpriteLibrary.getSprite("bsk"+(a+1)))),n[a].visible=!1,n[a].x=v[1].x,n[a].y=v[1].y,n[a].scaleX=1.2,n[a].scaleY=
1.2,s_oStage.addChild(n[a]);n[0].visible=!0;this.nextScene=function(){m++;this.loadBg(m);for(var y=0;36>y;y++)n[y].x=v[m].x,n[y].y=v[m].y;w.x=u.x=z[m].x;w.y=u.y=z[m].y;5===m&&(w.scaleX=u.scaleX=-1)};this.updateBasket=function(y){if(p){if(113<y.z&&120>y.z&&48<y.x&&67>y.x&&-8<y.y&&8>y.y)return p=!1,!0;if(!0===e&&!0===p)return e=!1}};this.scored=function(){if(14>d||28<=d&&35>=d)return this.playFrames(0,14,!1),!0;n[d].visible=!1;n[0].visible=!0;d=0;return!1};this.rimCollision=function(){if(35>d)return this.playFrames(28,
35,!1),!0;n[d].visible=!1;n[0].visible=!0;d=0;return!1};this.newBall=function(){e=!1;p=!0;d=0};this.getCartCoords=function(){return{x:u.x+CART_WIDTH/2,y:u.y+CART_HEIGHT/2}};this.loadBg=function(y){var g=3>=y?"field_camera_"+y:4===y?"field_camera_2":"field_camera_1";var r=s_oStage.getChildIndex(t);t=createBitmap(s_oSpriteLibrary.getSprite(g));3>y&&(t.scaleX=-1,t.x=CANVAS_WIDTH);s_oStage.removeChildAt(r);s_oStage.addChildAt(t,r)};this.playFrames=function(y,g,r){d<y||d>g||void 0===d?(n[d]&&(n[d].visible=
!1),d=y,f=n[d].visible=!0):(n[d].visible=!1,d===y&&!1===f?(f=!0,d+=1):d===g?!0===r?d=y:(f=!1,d--):f?d++:d--,n[d].visible=!0)};this.getBasketPos=function(y){return v[y]}}
function CPlayer(a,c){var b=!1,h=!1,p=!1,f=!0,e=void 0,d=1,m=[];this.init=function(n){for(var v=0;131>=v;v++)m.push(createBitmap(s_oSpriteLibrary.getSprite("player_"+s_iPlayerSelected+"_"+v))),m[v].visible=!1,m[v].regX=PLAYER_WIDTH/2,m[v].regY=PLAYER_HEIGHT/2,m[v].x=n.x-PLAYER_WIDTH,m[v].y=n.y-.55*PLAYER_HEIGHT,s_oStage.addChild(m[v])};this.nextScene=function(n){d++;this.newBall();if(5>d)for(var v=0;131>=v;v++)m[v].x=n.x-PLAYER_WIDTH,m[v].y=n.y-.55*PLAYER_HEIGHT;else for(v=0;131>=v;v++)m[v].x=n.x+
.05*PLAYER_WIDTH,m[v].y=n.y-.55*PLAYER_HEIGHT,m[v].scaleX=-1};this.idle1=function(){this.playFrames(0,15,!1)};this.grab1=function(){15>e?this.playFrames(0,15,!0):38>=e?(35===e&&(b=!0),this.playFrames(16,39,!0)):39===e&&!1===h&&(h=!0,a.ballWaitToThrow(),createjs.Tween.get(m[e]).to({scaleY:.98,y:c.y-.55*PLAYER_HEIGHT+5},450,createjs.Ease.linear).call(function(){createjs.Tween.get(m[e]).to({scaleY:1,y:c.y-.55*PLAYER_HEIGHT},450,createjs.Ease.linear).call(function(){h=!1})}))};this.grab2=function(){!b||
!0===b&&61>e?(this.playFrames(44,61,!0),57===e&&(b=!0)):!0===b&&61<=e&&!1===h&&(h=!0,a.ballWaitToThrow(),createjs.Tween.removeTweens(m[e]),createjs.Tween.get(m[e]).to({scaleY:.98,y:c.y-.55*PLAYER_HEIGHT+5},450,createjs.Ease.linear).call(function(){createjs.Tween.get(m[e]).to({scaleY:1,y:c.y-.55*PLAYER_HEIGHT},450,createjs.Ease.linear).call(function(){h=!1})}))};this.throwing=function(){if(43>e)this.playFrames(40,43,!0);else return!0};this.endTurn=function(){p?this.idle1():(this.playFrames(86,131,
!0),131===e&&(p=!0))};this.playFrames=function(n,v,z){e<n||e>v||void 0===e?(m[e]&&(m[e].visible=!1),e=n,f=m[e].visible=!0):(m[e].visible=!1,e===n&&!1===f?(f=!0,e+=1):e===v?!0===z?e=n:(f=!1,e--):f?e++:e--,m[e].visible=!0)};this.getPlCoords=function(){return{x:m[39].x-PLAYER_WIDTH/8,y:m[39].y-PLAYER_HEIGHT/10-BALL_SIZE/2}};this.isBallGrabbed=function(){return b};this.newBall=function(){p=h=b=!1};this.init(c)}
function CEndPanel(a,c,b,h){var p,f,e,d,m,n,v,z,t,w,u,q;this._init=function(B,y,g,r){p=r;u=new createjs.Container;u.visible=!1;s_oStage.addChild(u);w=new createjs.Shape;w.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);w.alpha=0;f=w.on("click",function(){});u.addChild(w);q=new createjs.Container;q.x=CANVAS_WIDTH/2;q.y=CANVAS_HEIGHT/2;u.addChild(q);var x=s_oSpriteLibrary.getSprite("msg_box");r=createBitmap(x);q.addChild(r);r=s_oSpriteLibrary.getSprite("players");var A=new createjs.SpriteSheet({images:[r],
frames:{width:r.width/3,height:r.height,regX:r.width/3/2,regY:0},animations:{player_0:0,player_1:1,player_2:2}});e=createSprite(A,"player_"+s_iPlayerSelected,r.width/3/2,0,r.width/3,r.height);e.x=-20;e.y=-20;q.addChild(e);d=new CTLText(q,20,20,x.width-40,52,52,"center","#fba500",FONT_GAME,1,0,0,TEXT_FINALSCORE+" "+y,!0,!0,!1,!1);d.setAlpha(0);createjs.Tween.get(d.getText()).to({alpha:1},1600,createjs.Ease.quadOut);m=new CTLText(q,20,100,x.width-40,52,36,"center","#fba500",FONT_GAME,1,0,0,TEXT_FINALSHOTS+
" "+g,!0,!0,!1,!1);m.setAlpha(0);createjs.Tween.get(m.getText()).wait(500).to({alpha:1},500,createjs.Ease.quadOut);B=0>=B?0:formatTime(B);n=new CTLText(q,20,150,x.width-40,52,36,"center","#fba500",FONT_GAME,1,0,0,TEXT_FINALTIME+" "+B,!0,!0,!1,!1);n.setAlpha(0);createjs.Tween.get(n.getText()).wait(750).to({alpha:1},500,createjs.Ease.quadOut);B=0===g?0:(y/g*100).toFixed(1);v=new CTLText(q,20,200,x.width-40,52,36,"center","#fba500",FONT_GAME,1,0,0,TEXT_FINALSUCCESSPERC+" "+B+"%",!0,!0,!1,!1);v.setAlpha(0);
var C=this;createjs.Tween.get(v.getText()).wait(1E3).to({alpha:1},500,createjs.Ease.quadOut).call(function(){t=new CGfxButton(x.width/2-200,x.height/2+125,s_oSpriteLibrary.getSprite("but_home"),q);t.addEventListener(ON_MOUSE_UP,C._onHome,C);var I=s_oSpriteLibrary.getSprite("but_restart");z=new CGfxButton(x.width/2+200,x.height/2+125,I,q);z.addEventListener(ON_MOUSE_UP,C._onButPlayAgain,C)},C);y>s_iBestScore&&(s_iBestScore=y,saveItem("street_basket_score_gd",y));q.regX=x.width/2;q.regY=x.height/2;
q.scale=.01;u.visible=!0;createjs.Tween.get(w).to({alpha:.8},500,createjs.Ease.cubicOut);createjs.Tween.get(q).wait(250).to({scale:.95},500,createjs.Ease.backOut);$(s_oMain).trigger("save_score",y);$(s_oMain).trigger("end_level")};this.unload=function(){$(s_oMain).trigger("show_interlevel_ad");w.off("click",f);z.unload();z=null};this._onButPlayAgain=function(){p.unload();s_oMain.gotoGame()};this._onHome=function(){p.unload()};this._init(a,c,b,h)}
function CCreditsPanel(){var a,c,b,h,p,f,e,d;this._init=function(){e=new createjs.Container;s_oStage.addChild(e);var m=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(m);m=s_oSpriteLibrary.getSprite("msg_box");c=createBitmap(m);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.regX=m.width/2;c.regY=m.height/2;e.addChild(c);p=new createjs.Shape;p.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);p.alpha=.01;d=p.on("click",function(){});e.addChild(p);m=s_oSpriteLibrary.getSprite("but_exit");
a=CANVAS_WIDTH/2+244;b=new CGfxButton(a,254,m,e);b.addEventListener(ON_MOUSE_UP,this.unload,this);h=new createjs.Text(TEXT_CREDITS_DEVELOPED,"36px "+FONT_GAME,"#ffffff");h.x=CANVAS_WIDTH/2;h.y=290;h.textAlign="center";e.addChild(h);m=s_oSpriteLibrary.getSprite("logo_credits");var n=createBitmap(m);n.regX=m.width/2;n.regY=m.height/2;n.x=CANVAS_WIDTH/2;n.y=390;e.addChild(n);f=new createjs.Text("www.codethislab.com","36px "+FONT_GAME,"#ffffff");f.x=CANVAS_WIDTH/2;f.y=450;f.textAlign="center";e.addChild(f)};
this.unload=function(){p.off("click",d);b.unload();b=null;s_oStage.removeChild(e)};this._init()}
CTLText.prototype={constructor:CTLText,__autofit:function(){if(this._bFitText){for(var a=this._iStartingFontSize;(this._oText.getBounds().height>this._iHeight-2*this._iPaddingV||this._oText.getBounds().width>this._iWidth-2*this._iPaddingH)&&!(a--,this._oText.font=a+"px "+this._szFont,this._oText.lineHeight=Math.round(a*this._fLineHeightFactor),this.__updateY(),this.__verticalAlign(),8>a););this._iFontSize=a}},__verticalAlign:function(){if(this._bVerticalAlign){var a=this._oText.getBounds().height;
this._oText.y-=(a-this._iHeight)/2+this._iPaddingV}},__updateY:function(){this._oText.y=this._y+this._iPaddingV;switch(this._oText.textBaseline){case "middle":this._oText.y+=this._oText.lineHeight/2+(this._iFontSize*this._fLineHeightFactor-this._iFontSize)}},__createText:function(a){this._bDebug&&(this._oDebugShape=new createjs.Shape,this._oDebugShape.graphics.beginFill("rgba(255,0,0,0.5)").drawRect(this._x,this._y,this._iWidth,this._iHeight),this._oContainer.addChild(this._oDebugShape));this._oText=
new createjs.Text(a,this._iFontSize+"px "+this._szFont,this._szColor);this._oText.textBaseline="middle";this._oText.lineHeight=Math.round(this._iFontSize*this._fLineHeightFactor);this._oText.textAlign=this._szAlign;this._oText.lineWidth=this._bMultiline?this._iWidth-2*this._iPaddingH:null;switch(this._szAlign){case "center":this._oText.x=this._x+this._iWidth/2;break;case "left":this._oText.x=this._x+this._iPaddingH;break;case "right":this._oText.x=this._x+this._iWidth-this._iPaddingH}this._oContainer.addChild(this._oText);
this.refreshText(a)},setVerticalAlign:function(a){this._bVerticalAlign=a},setOutline:function(a){null!==this._oText&&(this._oText.outline=a)},setShadow:function(a,c,b,h){null!==this._oText&&(this._oText.shadow=new createjs.Shadow(a,c,b,h))},setColor:function(a){this._oText.color=a},setAlpha:function(a){this._oText.alpha=a},setPos:function(a,c){this._x=a;this._y=c;this._oText.x=a;this._oText.y=c},removeTweens:function(){createjs.Tween.removeTweens(this._oText)},getText:function(){return this._oText},
getY:function(){return this._y},getFontSize:function(){return this._iFontSize},refreshText:function(a){""===a&&(a=" ");null===this._oText&&this.__createText(a);this._oText.text=a;this._oText.font=this._iStartingFontSize+"px "+this._szFont;this._oText.lineHeight=Math.round(this._iStartingFontSize*this._fLineHeightFactor);this.__autofit();this.__updateY();this.__verticalAlign()}};
function CTLText(a,c,b,h,p,f,e,d,m,n,v,z,t,w,u,q,B){this._oContainer=a;this._x=c;this._y=b;this._iWidth=h;this._iHeight=p;this._bMultiline=q;this._iStartingFontSize=this._iFontSize=f;this._szAlign=e;this._szColor=d;this._szFont=m;this._iPaddingH=v;this._iPaddingV=z;this._bVerticalAlign=u;this._bFitText=w;this._bDebug=B;this._oDebugShape=null;this._fLineHeightFactor=n;this._oText=null;t&&this.__createText(t)}
function CMenuMode(){var a,c,b,h,p,f,e,d,m,n,v,z,t,w,u,q,B=null,y=null,g,r,x,A,C,I=this;this._init=function(){C=new createjs.Container;s_oStage.addChild(C);var k=createBitmap(s_oSpriteLibrary.getSprite("bg_selection"));C.addChild(k);k=s_oSpriteLibrary.getSprite("choose_player_text_"+s_iCurLang);z=createBitmap(k);z.regX=k.width/2;z.x=CANVAS_WIDTH/2;z.y=90;C.addChild(z);k=s_oSpriteLibrary.getSprite("player_selection_0");var G={images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:k.height/
2},animations:{state_off:0,state_on:1}};G=new createjs.SpriteSheet(G);g=createSprite(G,"state_on",k.width/2/2,k.height/2,k.width/2,k.height);g.x=CANVAS_WIDTH/2-260;g.y=CANVAS_HEIGHT/2;m=g.on("click",this._onSelect0,this);C.addChild(g);k=s_oSpriteLibrary.getSprite("player_selection_1");G={images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:k.height/2},animations:{state_off:0,state_on:1}};G=new createjs.SpriteSheet(G);r=createSprite(G,"state_off",k.width/2/2,k.height/2,k.width/
2,k.height);r.x=CANVAS_WIDTH/2+260;r.y=CANVAS_HEIGHT/2;n=r.on("click",this._onSelect1,this);C.addChild(r);k=s_oSpriteLibrary.getSprite("player_selection_2");G={images:[k],frames:{width:k.width/2,height:k.height,regX:k.width/2/2,regY:k.height/2},animations:{state_off:0,state_on:1}};G=new createjs.SpriteSheet(G);x=createSprite(G,"state_off",k.width/2/2,k.height/2,k.width/2,k.height);x.x=CANVAS_WIDTH/2;x.y=CANVAS_HEIGHT/2;v=x.on("click",this._onSelect2,this);C.addChild(x);A=new CGfxButton(CANVAS_WIDTH/
2+420,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("but_next"),C);A.addEventListener(ON_MOUSE_UP,this._onNext,this);k=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-k.width/2-10;c=k.height/2+10;w=new CGfxButton(a,c,k,C);w.addEventListener(ON_MOUSE_UP,this._onExit,this);G=s_oSpriteLibrary.getSprite("but_lang");!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(k=s_oSpriteLibrary.getSprite("audio_icon"),e=a-k.width/2-10,d=c,u=new CToggle(e,d,k,s_bAudioActive,s_oStage),u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this),b=e-G.width/NUM_LANGUAGES-10,h=d):(b=CANVAS_WIDTH-k.width/4-10,h=k.height/2+10);t=new CButLang(b,h,NUM_LANGUAGES,s_iCurLang,G,s_oStage);t.addEventListener(ON_SELECT_LANG,this._onChangeLang,this);k=window.document;G=k.documentElement;B=G.requestFullscreen||G.mozRequestFullScreen||G.webkitRequestFullScreen||G.msRequestFullscreen;y=k.exitFullscreen||k.mozCancelFullScreen||k.webkitExitFullscreen||k.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(B=!1);B&&screenfull.isEnabled&&(k=s_oSpriteLibrary.getSprite("but_fullscreen"),
p=k.width/4+10,f=k.height/2+10,q=new CToggle(p,f,k,s_bFullscreen,s_oStage),q.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));this.refreshButtonPos()};this.unload=function(){w.unload();A.unload();g.off("click",m);r.off("click",n);x.off("click",v);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null;B&&screenfull.isEnabled&&q.unload();t.unload();s_oStage.removeChild(C);s_oModeMenu=null};this.refreshButtonPos=function(){w.setPosition(a-s_iOffsetX,c+s_iOffsetY);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||u.setPosition(e-s_iOffsetX,s_iOffsetY+d);B&&screenfull.isEnabled&&q.setPosition(p+s_iOffsetX,f+s_iOffsetY);t.setPosition(b-s_iOffsetX,h+s_iOffsetY)};this._onChangeLang=function(k){s_iCurLang=k;refreshLanguage();k=s_oSpriteLibrary.getSprite("choose_player_text_"+s_iCurLang);z.image=k;z.regX=k.width/2};this._onSelect0=function(){g.gotoAndStop("state_on");r.gotoAndStop("state_off");x.gotoAndStop("state_off");s_iPlayerSelected=0};this._onSelect1=function(){g.gotoAndStop("state_off");r.gotoAndStop("state_on");
x.gotoAndStop("state_off");s_iPlayerSelected=1};this._onSelect2=function(){g.gotoAndStop("state_off");r.gotoAndStop("state_off");x.gotoAndStop("state_on");s_iPlayerSelected=2};this._onNext=function(){I.unload();s_oMain.gotoGame()};this._onExit=function(){s_oModeMenu.unload();s_oMain.gotoMenu()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){B&&screenfull.isEnabled&&q.setActive(s_bFullscreen)};this._onFullscreenRelease=
function(){s_bFullscreen?y.call(window.document):B.call(window.document.documentElement);sizeHandler()};s_oModeMenu=this;this._init()}var s_oModeMenu=null;
function CAreYouSurePanel(a){var c,b,h,p,f,e,d,m,n,v=this;this._init=function(){c=[];b=[];m=new createjs.Container;m.visible=!1;z.addChild(m);h=new createjs.Shape;h.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;d=h.on("click",function(){});m.addChild(h);n=new createjs.Container;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2;m.addChild(n);var t=s_oSpriteLibrary.getSprite("msg_box"),w=createBitmap(t);n.addChild(w);p=new CTLText(n,20,20,t.width-40,200,100,"center","#fba500",FONT_GAME,
1,0,0," ",!0,!0,!0,!1);f=new CGfxButton(t.width/2+150,300,s_oSpriteLibrary.getSprite("but_yes"),n);f.addEventListener(ON_MOUSE_UP,this._onReleaseYes,this);e=new CGfxButton(t.width/2-150,300,s_oSpriteLibrary.getSprite("but_no"),n);e.addEventListener(ON_MOUSE_UP,this._onReleaseNo,this);n.regX=n.getBounds().width/2;n.regY=n.getBounds().height/2};this.addEventListener=function(t,w,u){c[t]=w;b[t]=u};this.unload=function(){h.off("click",d);e.unload();f.unload()};this.show=function(t){p.refreshText(t);n.scale=
.01;m.visible=!0;createjs.Tween.get(h).to({alpha:.8},500,createjs.Ease.cubicOut);createjs.Tween.get(n).wait(250).to({scale:.95},500,createjs.Ease.backOut)};this.hide=function(){createjs.Tween.get(h).wait(250).to({alpha:0},500,createjs.Ease.cubicOut);createjs.Tween.get(n).to({scale:.01},500,createjs.Ease.backIn).call(function(){m.visible=!1})};this._onReleaseYes=function(){c[ON_RELEASE_YES]&&c[ON_RELEASE_YES].call(b[ON_RELEASE_YES])};this._onReleaseNo=function(){c[ON_RELEASE_NO]&&c[ON_RELEASE_NO].call(b[ON_RELEASE_NO]);
v.hide()};var z=a;this._init(a)}
function CScoreTextAnim(a,c,b,h,p){var f;this._init=function(e,d,m,n){f=new createjs.Container;f.x=d;f.y=m;f.alpha=0;p.addChild(f);e=new createjs.Text(e,"50px "+FONT_GAME,n);e.textAlign="center";e.shadow=new createjs.Shadow("#000",1,1,1);f.addChild(e);e=f.getBounds();f.cache(e.x,e.y,e.width,e.height);var v=this;createjs.Tween.get(f).to({alpha:1},200,createjs.Ease.quadIn).call(function(){v.moveUp()})};this.moveUp=function(){var e=f.y-400,d=this;createjs.Tween.get(f).to({y:e},1500,createjs.Ease.sineIn).call(function(){d.unload()});
createjs.Tween.get(f).wait(800).to({alpha:0},500)};this.unload=function(){p.removeChild(f)};this._init(a,c,b,h)}
function CAlertSavingBox(a,c){var b,h,p,f,e;this._init=function(n){e=new createjs.Container;m.addChild(e);h=new createjs.Shape;h.graphics.beginFill("#000").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;b=h.on("click",function(){});e.addChild(h);f=new createjs.Container;f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;e.addChild(f);var v=s_oSpriteLibrary.getSprite("msg_box"),z=createBitmap(v);f.addChild(z);new CTLText(f,20,20,v.width-40,200,28,"center","#fba500",FONT_GAME,1,14,7,n,!0,!0,!0,!1);p=new CGfxButton(v.width/
2,v.height/2+110,s_oSpriteLibrary.getSprite("but_yes"),f);p.addEventListener(ON_MOUSE_UP,this._onButOk,this);f.regX=f.getBounds().width/2;f.regY=f.getBounds().height/2;f.scale=.01;e.visible=!0;createjs.Tween.get(h).to({alpha:.8},500,createjs.Ease.cubicOut);createjs.Tween.get(f).wait(250).to({scale:.95},500,createjs.Ease.backOut)};this._onButOk=function(){d.unload()};this.unload=function(){h.off("click",b);p.unload();m.removeChild(e)};var d=this;var m=c;this._init(a)}
function CButLang(a,c,b,h,p,f){var e=h,d,m,n,v,z,t;this._init=function(w,u,q,B){d=[];m=[];t=new createjs.Container;t.x=w;t.y=u;v=t.on("mousedown",this._onPress,this);n=t.on("click",this._onChangeLang,this);f.addChild(t);w={};for(u=0;u<q;u++)w["lang_"+u]=u;w=new createjs.SpriteSheet({images:[B],frames:{width:B.width/q,height:B.height},animations:w});z=createSprite(w,"lang_"+e,0,0,B.width/q,B.height);t.addChild(z);t.regX=B.width/q/2;t.regY=B.height/2};this.unload=function(){t.off("mousedown",v);t.off("click",
n)};this.addEventListener=function(w,u,q){d[w]=u;m[w]=q};this.setPosition=function(w,u){t.x=w;t.y=u};this._onPress=function(){t.scale=.9};this._onChangeLang=function(){t.scale=1;e++;e===b&&(e=0);z.gotoAndStop("lang_"+e);d[ON_SELECT_LANG]&&d[ON_SELECT_LANG].call(m[ON_SELECT_LANG],e)};this._init(a,c,b,p)};